---
- name: Ensure dependencies are installed
  apt:
    name: "{{ sysctl_dependencies }}"
    state: present
    update_cache: true

- name: Ensure sysctl entries are set
  sysctl:
    name: "{{ item.name }}"
    reload: "{{ item.reload | d(true) }}"
    sysctl_file: "{{ item.sysctl_file | d(omit) }}"
    sysctl_set: "{{ item.sysctl_set | d(omit) }}"
    value: "{{ item.value }}"
  loop: "{{ sysctl_entries }}"
  loop_control:
    label: "{{ item.name }}"
