---
dependency:
  name: galaxy
  enabled: False

driver:
  name: docker

platforms:
  - name: ansible-role-sysctl-debian-10
    image: debian:10
    privileged: true
  - name: ansible-role-sysctl-debian-11
    image: debian:11
    privileged: true
  - name: ansible-role-sysctl-ubuntu-2004
    image: ubuntu:20.04
    privileged: true
  - name: ansible-role-sysctl-ubuntu-2204
    image: ubuntu:22.04
    privileged: true

provisioner:
  name: ansible

verifier:
  name: testinfra
