---
dependency:
  name: galaxy
  enbaled: False

driver:
  name: docker

platforms:
  - name: ansible-role-sysctl-debian-9
    image: debian:9
    privileged: true
  - name: ansible-role-sysctl-debian-10
    image: debian:10
    privileged: true
  - name: ansible-role-sysctl-ubuntu-1804
    image: ubuntu:18.04
    privileged: true
  - name: ansible-role-sysctl-ubuntu-2004
    image: ubuntu:20.04
    privileged: true

lint: |
    yamllint .
    ansible-lint
    flake8

provisioner:
  name: ansible

verifier:
  name: testinfra
